baseURL = "http://example.org/"
languageCode = "en-us"
theme = "github-project-landing-page"

title = "Flux CD"

[params]
	description = "Flux - the Kubernetes Gitops operator"
	#author_url = ""

	project_url = "https://github.com/fluxcd/flux"
	github_project_name = "flux"
	github_user_name = "fluxcd"
